import type { Poll, Vendor } from './types'

// ─── Seed Polls ───────────────────────────────────────────────────────────────
// Pre-populated so the feed isn't empty on first load.

export const SEED_POLLS: Poll[] = [
  {
    id: 'seed-1',
    authorName: 'Priya M.',
    question: 'Which lehenga silhouette for the main ceremony?',
    options: [
      { label: 'A-line flared', imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400' },
      { label: 'Straight fitted', imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400' },
    ],
    votes: { 0: 14, 1: 9 },
    comments: [
      { id: 'c1', authorName: 'Ananya', text: 'A-line is so timeless 😍', createdAt: '2026-04-18T10:00:00Z' },
      { id: 'c2', authorName: 'Mehak', text: 'Depends on the venue! Straight looks fab for indoor.', createdAt: '2026-04-18T11:30:00Z' },
    ],
    tags: ['Lehenga', 'Outfit'],
    createdAt: '2026-04-18T09:00:00Z',
  },
  {
    id: 'seed-2',
    authorName: 'Shreya K.',
    question: 'Pastel florals or jewel-toned decor for the mandap?',
    options: [
      { label: 'Pastel florals', imageUrl: 'https://images.unsplash.com/photo-1519741347686-c1e331c20a2d?w=400' },
      { label: 'Jewel tones', imageUrl: 'https://images.unsplash.com/photo-1606216794079-73b6c3a69f68?w=400' },
    ],
    votes: { 0: 22, 1: 11 },
    comments: [
      { id: 'c3', authorName: 'Divya', text: 'Pastel all the way — so dreamy for photos!', createdAt: '2026-04-17T14:00:00Z' },
    ],
    tags: ['Decor', 'Mandap'],
    createdAt: '2026-04-17T12:00:00Z',
  },
  {
    id: 'seed-3',
    authorName: 'Naina R.',
    question: 'Which photography style do you prefer?',
    options: [
      { label: 'Candid documentary', imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400' },
      { label: 'Classic portraits', imageUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=400' },
    ],
    votes: { 0: 31, 1: 8 },
    comments: [
      { id: 'c4', authorName: 'Riya', text: 'Candid wins, those in-between moments are gold 📸', createdAt: '2026-04-16T08:00:00Z' },
      { id: 'c5', authorName: 'Sonali', text: 'We did both — totally worth it!', createdAt: '2026-04-16T09:00:00Z' },
    ],
    tags: ['Photography'],
    createdAt: '2026-04-16T07:00:00Z',
  },
  {
    id: 'seed-4',
    authorName: 'Isha P.',
    question: 'Mehndi night vibe: intimate garden or full banquet?',
    options: [
      { label: 'Intimate garden', imageUrl: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400' },
      { label: 'Full banquet hall', imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400' },
    ],
    votes: { 0: 19, 1: 7 },
    comments: [],
    tags: ['Mehndi', 'Events'],
    createdAt: '2026-04-15T16:00:00Z',
  },
]

// ─── Mock Vendors ──────────────────────────────────────────────────────────────

export const VENDORS: Vendor[] = [
  // Photographers
  {
    id: 'v1',
    name: 'Frosted Frames',
    category: 'Photographer',
    location: 'Mumbai',
    priceRange: '₹2.5L–₹4L',
    rating: 4.9,
    reviewCount: 84,
    description: 'Award-winning candid wedding photographers capturing raw, cinematic moments. Specialise in South Asian weddings.',
    imageUrl: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=500',
    tags: ['Candid', 'Cinematic', 'South Asian'],
    available: true,
  },
  {
    id: 'v2',
    name: 'Ishq Stories',
    category: 'Photographer',
    location: 'Delhi',
    priceRange: '₹1.8L–₹3L',
    rating: 4.7,
    reviewCount: 112,
    description: 'Storytelling through light and emotion. Drone coverage, same-day edits, and a 500-photo album guaranteed.',
    imageUrl: 'https://images.unsplash.com/photo-1519741347686-c1e331c20a2d?w=500',
    tags: ['Drone', 'Same-day Edit', 'Albums'],
    available: true,
  },
  // Decorators
  {
    id: 'v3',
    name: 'Gulmohar Studio',
    category: 'Decorator',
    location: 'Jaipur',
    priceRange: '₹5L–₹12L',
    rating: 4.8,
    reviewCount: 56,
    description: 'Floral design studio known for ceiling installs and lush mandap arrangements. Featured in Vogue Weddings.',
    imageUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=500',
    tags: ['Floral', 'Mandap', 'Luxury'],
    available: true,
  },
  {
    id: 'v4',
    name: 'Noor Decor',
    category: 'Decorator',
    location: 'Mumbai',
    priceRange: '₹3L–₹7L',
    rating: 4.6,
    reviewCount: 73,
    description: 'Candlelit, pastel, and moonlit aesthetics. Specialise in small-to-midsize intimate events.',
    imageUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=500',
    tags: ['Pastel', 'Intimate', 'Candlelit'],
    available: false,
  },
  // Caterers
  {
    id: 'v5',
    name: 'Annapurna Catering',
    category: 'Caterer',
    location: 'Delhi',
    priceRange: '₹1,200–₹2,200 per plate',
    rating: 4.7,
    reviewCount: 145,
    description: 'Pan-India menu specialists. Live chaat counters, chefs on site, and impeccable hygiene ratings.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=500',
    tags: ['Pan-India', 'Live Counters', 'Vegetarian'],
    available: true,
  },
  {
    id: 'v6',
    name: 'Nawabi Dawat',
    category: 'Caterer',
    location: 'Lucknow',
    priceRange: '₹1,800–₹3,500 per plate',
    rating: 4.9,
    reviewCount: 61,
    description: 'Authentic Awadhi and Mughlai cuisine. Dum biryani, kebabs, and dessert stations that guests talk about for years.',
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=500',
    tags: ['Mughlai', 'Biryani', 'Premium'],
    available: true,
  },
  // Mehendi Artists
  {
    id: 'v7',
    name: 'Henna by Zara',
    category: 'Mehendi Artist',
    location: 'Mumbai',
    priceRange: '₹25K–₹60K',
    rating: 4.9,
    reviewCount: 203,
    description: 'Intricate bridal mehendi with hidden motifs and dulha portraits. Booked 6 months in advance on average.',
    imageUrl: 'https://images.unsplash.com/photo-1591453089816-0fbb971b454c?w=500',
    tags: ['Bridal', 'Portrait', 'Intricate'],
    available: true,
  },
  // Makeup Artists
  {
    id: 'v8',
    name: 'Aarohi Bridal',
    category: 'Makeup Artist',
    location: 'Delhi',
    priceRange: '₹30K–₹80K',
    rating: 4.8,
    reviewCount: 176,
    description: 'HD bridal makeup, airbrush foundation, and a team of 3 for quick turnarounds on big wedding days.',
    imageUrl: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=500',
    tags: ['HD Makeup', 'Airbrush', 'Team'],
    available: true,
  },
  // Venues
  {
    id: 'v9',
    name: 'The Leela Palace',
    category: 'Venue',
    location: 'Udaipur',
    priceRange: '₹25L–₹60L',
    rating: 4.9,
    reviewCount: 38,
    description: 'Lakeside palace venue with 5-star hospitality, rooftop ceremonies, and full wedding weekend packages.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500',
    tags: ['Palace', 'Lakeside', 'Destination'],
    available: true,
  },
  {
    id: 'v10',
    name: 'Fern & Willow Farmhouse',
    category: 'Venue',
    location: 'Gurgaon',
    priceRange: '₹8L–₹18L',
    rating: 4.7,
    reviewCount: 55,
    description: 'Lush 3-acre farmhouse with both indoor and outdoor spaces. Loved for its garden ceremony and fairy-light canopies.',
    imageUrl: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500',
    tags: ['Farmhouse', 'Garden', 'Fairy Lights'],
    available: false,
  },
]
